env: "dev"
postgres:
  host: "localhost"
  port: "5432"
  user: "wbuser" 
  password: "wbwbwb" 
  db_name: "wb" 
http_server:
  address: "localhost:8082" 
  timeout: 4s
  idle_timeout: 60s
nats:
  cluster_id: "test-cluster" # имя кластера
  client_id: "client-123" # имя клиента
  url: "nats://localhost:4222" # ссылка для подключения к nats